app:
  version: @project.version@-@timestamp@
# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 56000
  servlet:
    context-path: /api
    session:
      cookie:
        http-only: true
spring:
  application:
    name: xsy-base-demo
  # 环境 dev|test|prod
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
      enabled: true
  datasource:
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  task:
    scheduling:
      pool:
        size: 10
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      logic-delete-field: isDelete
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
fdfs:
  # 读取时间
  soTimeout: 1500
  # 连接超时时间
  connectTimeout: 1500
  # 编码默认UTF-8，charset属性不能自定义
  # charset: UTF-8
  # 缩略图
  thumbImage:
    # 宽
    width: 150
    # 高
    height: 150
