logging:
  level:
    com.xsy: debug
  file:
    max-size: 100MB
    max-history: 3
    name: /var/log/${spring.application.name}/${spring.application.name}-${spring.profiles.active}.log
spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.24:3306/web_base_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: xiangsuyuan
